/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'elev4' at '2016-05-31 15:18' with Gradle 2.13
 *
 * @author elev4, @date 2016-05-31 15:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
